### ISSUE TITLE
Unable to Reproduce Paper Code

### ISSUE THREAD

**Issue by zhihuipikaqiu** [Henrium/MolSets#1]
Dear Researcher,

Thank you for your scientific contributions and for sharing them with the community. While studying your research findings, we noticed that the shared data is in PKL format, which makes it difficult for us to understand the original data structure or to use your code with other datasets.

Could you please share the organized dataset you used in your experiments, as well as the processes involved in handling it? We are particularly puzzled about how the PKL files were generated and are unable to grasp the original input and output of the model.

We hope for your assistance and send our best wishes.

**Comment by Henrium** [comment]
Thanks for your interest. The pkl files are organized datasets, we've added descriptions in README. The raw data can be found in the referenced paper.

**Comment by himanshisyadav** [comment]
Can you outline the process used to produce the molecular graphs? I do have access to the original dataset and the pkl dataset. However, it is unclear how to convert the original dataset into the pkl dataset.

**Comment by Henrium** [comment]
> Can you outline the process used to produce the molecular graphs? I do have access to the original dataset and the pkl dataset. However, it is unclear how to convert the original dataset into the pkl dataset.

A rough procedure is (1) convert SMILES to graph using `torch_teometric` and `rdkit`, (2) for the same electrolyte, fit $\log \sigma$ - $1/T$ to get the response (298 K conductivity), and (3) assemble graphs, weight fractions, molecular weights, and responses into a `pkl`.

In our follow-up work, we will release the code for converting materials data into graphs.
